version: "3.8"
services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    container_name: web
    image: pankistodor/yamdb_final:latest
    restart: always
    volumes:
      - static_value:/code/static/
    depends_on:
      - db
    expose:
      - 8000
    env_file:
      - ./.env
  nginx:
    container_name: nginx
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web
volumes:
  postgres_data:
  static_value:
  media_value: